[package]
name = "color"
version = "0.1.0"
authors = ["John Smith <john.smith@debug-pro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2"
